def n_plus_1 (n) :
    result = n + 1

n_plus_1(3)
print(result)

# 에러가 발생 result를 함수 내에서만 사용해서
